Posttest 7 Pengenalan Tensorflow

In [31]:
# Import Library | pandas | Matplotlib | sklearn
import tensorflow as tf
import numpy as np

# Import untuk menghilangkan warning 
import warnings
warnings.filterwarnings('ignore')

In [32]:
# Membuat tensor dengan shape (5,5) dengan nilai random

rd_tensor = tf.random.normal([5,5], mean=0., stddev=1., seed=2)
rd_tensor.numpy()

array([[ 0.23604095,  0.8829411 ,  1.1772621 ,  0.16941217, -0.69530165],
       [-0.12090585,  1.1120238 ,  0.16127758,  1.6483933 ,  0.6654914 ],
       [ 1.1746731 , -0.51929307,  0.868432  , -1.9305269 ,  0.9412249 ],
       [ 0.23267265, -2.157521  ,  0.3326458 ,  0.42493948,  0.28247148],
       [-1.1424482 , -1.2732137 ,  0.5971868 ,  0.39083976, -0.21846044]],
      dtype=float32)

In [33]:
# Membuat tensor dengan shape (5,5) dengan nilai bilangan prima

prnum = [[2, 3, 5, 7, 11],
          [13, 17, 19, 23, 29],
          [31, 37, 41, 43, 47],
          [53, 59, 61, 71, 73],
          [79, 83, 89, 97, 101]]

pr_tensor = tf.constant(prnum, dtype=tf.float32)
print(pr_tensor)

tf.Tensor(
[[  2.   3.   5.   7.  11.]
 [ 13.  17.  19.  23.  29.]
 [ 31.  37.  41.  43.  47.]
 [ 53.  59.  61.  71.  73.]
 [ 79.  83.  89.  97. 101.]], shape=(5, 5), dtype=float32)


In [34]:
# rd_tensor Dimension
print(rd_tensor.shape)

(5, 5)


In [35]:
# pr_tensor Dimension
print(pr_tensor.shape)

(5, 5)


In [36]:
# Operasi Aritmatika pada tensor

In [37]:
# Penambahan
print(tf.add(rd_tensor, pr_tensor).numpy())

[[  2.236041    3.8829412   6.1772623   7.169412   10.304698 ]
 [ 12.879094   18.112024   19.161278   24.648394   29.665491 ]
 [ 32.174675   36.480705   41.86843    41.069473   47.941223 ]
 [ 53.232674   56.84248    61.332645   71.42494    73.28247  ]
 [ 77.85755    81.72678    89.59718    97.39084   100.78154  ]]


In [38]:
# Pengurangan
print(tf.subtract(rd_tensor, pr_tensor).numpy())

[[  -1.763959    -2.1170588   -3.822738    -6.830588   -11.695302 ]
 [ -13.120906   -15.887976   -18.838722   -21.351606   -28.334509 ]
 [ -29.825327   -37.519295   -40.13157    -44.930527   -46.058777 ]
 [ -52.767326   -61.15752    -60.667355   -70.57506    -72.71753  ]
 [ -80.14245    -84.27322    -88.40282    -96.60916   -101.21846  ]]


In [39]:
# Perkalian
print(tf.multiply(rd_tensor, pr_tensor).numpy())

[[   0.4720819    2.6488233    5.8863106    1.1858852   -7.6483183]
 [  -1.5717762   18.904406     3.064274    37.913044    19.299252 ]
 [  36.414864   -19.213844    35.605713   -83.01266     44.237568 ]
 [  12.331651  -127.29374     20.291393    30.170704    20.620419 ]
 [ -90.25341   -105.67674     53.149624    37.911457   -22.064505 ]]


In [40]:
# Pembagian
print(tf.divide(rd_tensor, pr_tensor).numpy())

[[ 0.11802047  0.2943137   0.23545241  0.02420174 -0.06320924]
 [-0.00930045  0.06541317  0.00848829  0.07166927  0.02294798]
 [ 0.03789268 -0.01403495  0.02118127 -0.04489597  0.02002606]
 [ 0.00439005 -0.03656815  0.00545321  0.00598506  0.00386947]
 [-0.01446137 -0.01533992  0.00670996  0.00402928 -0.00216297]]


In [41]:
# Perpangkatan
print(tf.pow(rd_tensor, pr_tensor).numpy())

[[ 5.5715330e-02  6.8832767e-01  2.2613394e+00  4.0050891e-06
  -1.8361403e-02]
 [-1.1798187e-12  6.0805044e+00  8.7883194e-16  9.8265070e+04
   7.4324334e-06]
 [ 1.4703729e+02 -2.9530003e-11  3.0772886e-03 -1.9233636e+12
   5.8021586e-02]
 [ 2.7384353e-34 -5.0506467e+19  6.9327414e-30  4.0852918e-27
   0.0000000e+00]
 [-3.7075285e+04 -5.0910739e+08  1.1852447e-20  0.0000000e+00
  -0.0000000e+00]]


In [42]:
# Maximum
print(tf.math.maximum(rd_tensor, pr_tensor).numpy())

[[  2.   3.   5.   7.  11.]
 [ 13.  17.  19.  23.  29.]
 [ 31.  37.  41.  43.  47.]
 [ 53.  59.  61.  71.  73.]
 [ 79.  83.  89.  97. 101.]]


In [43]:
# Minimum
print(tf.math.minimum(rd_tensor, pr_tensor).numpy())

[[ 0.23604095  0.8829411   1.1772621   0.16941217 -0.69530165]
 [-0.12090585  1.1120238   0.16127758  1.6483933   0.6654914 ]
 [ 1.1746731  -0.51929307  0.868432   -1.9305269   0.9412249 ]
 [ 0.23267265 -2.157521    0.3326458   0.42493948  0.28247148]
 [-1.1424482  -1.2732137   0.5971868   0.39083976 -0.21846044]]


In [44]:
# Menampilkan nilai maksimal dan minimal variabel rd_tensor

In [45]:
# Maksimum
print(tf.reduce_max(rd_tensor).numpy())

1.6483933


In [46]:
# Minimum
print(tf.reduce_min(rd_tensor).numpy())

-2.157521


In [47]:
# Menggabungkan variabel rd_tensor dengan pr_tensor (Concatenation)

In [48]:
# Kolom 0
print(tf.concat([rd_tensor, pr_tensor], axis=0).numpy())

[[  0.23604095   0.8829411    1.1772621    0.16941217  -0.69530165]
 [ -0.12090585   1.1120238    0.16127758   1.6483933    0.6654914 ]
 [  1.1746731   -0.51929307   0.868432    -1.9305269    0.9412249 ]
 [  0.23267265  -2.157521     0.3326458    0.42493948   0.28247148]
 [ -1.1424482   -1.2732137    0.5971868    0.39083976  -0.21846044]
 [  2.           3.           5.           7.          11.        ]
 [ 13.          17.          19.          23.          29.        ]
 [ 31.          37.          41.          43.          47.        ]
 [ 53.          59.          61.          71.          73.        ]
 [ 79.          83.          89.          97.         101.        ]]


In [49]:
# Kolom 1
print(tf.concat([rd_tensor, pr_tensor], axis=1).numpy())

[[  0.23604095   0.8829411    1.1772621    0.16941217  -0.69530165
    2.           3.           5.           7.          11.        ]
 [ -0.12090585   1.1120238    0.16127758   1.6483933    0.6654914
   13.          17.          19.          23.          29.        ]
 [  1.1746731   -0.51929307   0.868432    -1.9305269    0.9412249
   31.          37.          41.          43.          47.        ]
 [  0.23267265  -2.157521     0.3326458    0.42493948   0.28247148
   53.          59.          61.          71.          73.        ]
 [ -1.1424482   -1.2732137    0.5971868    0.39083976  -0.21846044
   79.          83.          89.          97.         101.        ]]


In [50]:
# Tensor Sorting

In [51]:
# Descending | rd_tensor
print(tf.sort(rd_tensor, direction='DESCENDING'))

tf.Tensor(
[[ 1.1772621   0.8829411   0.23604095  0.16941217 -0.69530165]
 [ 1.6483933   1.1120238   0.6654914   0.16127758 -0.12090585]
 [ 1.1746731   0.9412249   0.868432   -0.51929307 -1.9305269 ]
 [ 0.42493948  0.3326458   0.28247148  0.23267265 -2.157521  ]
 [ 0.5971868   0.39083976 -0.21846044 -1.1424482  -1.2732137 ]], shape=(5, 5), dtype=float32)


In [52]:
# Ascending | rd_tensor
print(tf.sort(rd_tensor, direction='ASCENDING'))

tf.Tensor(
[[-0.69530165  0.16941217  0.23604095  0.8829411   1.1772621 ]
 [-0.12090585  0.16127758  0.6654914   1.1120238   1.6483933 ]
 [-1.9305269  -0.51929307  0.868432    0.9412249   1.1746731 ]
 [-2.157521    0.23267265  0.28247148  0.3326458   0.42493948]
 [-1.2732137  -1.1424482  -0.21846044  0.39083976  0.5971868 ]], shape=(5, 5), dtype=float32)


In [53]:
# Descending | pr_tensor
print(tf.sort(pr_tensor, direction='DESCENDING'))

tf.Tensor(
[[ 11.   7.   5.   3.   2.]
 [ 29.  23.  19.  17.  13.]
 [ 47.  43.  41.  37.  31.]
 [ 73.  71.  61.  59.  53.]
 [101.  97.  89.  83.  79.]], shape=(5, 5), dtype=float32)


In [54]:
# Ascending | pr_tensor
print(tf.sort(pr_tensor, direction='ASCENDING'))

tf.Tensor(
[[  2.   3.   5.   7.  11.]
 [ 13.  17.  19.  23.  29.]
 [ 31.  37.  41.  43.  47.]
 [ 53.  59.  61.  71.  73.]
 [ 79.  83.  89.  97. 101.]], shape=(5, 5), dtype=float32)


In [55]:
# :D #